2023-11-27 10:35:54,374 ERROR: Exception on / [GET] [in C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\routes.py", line 37, in index
    return render_template('index.html', title='Home', form=form,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2023-11-27 10:35:54,454 ERROR: Exception on / [GET] [in C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\routes.py", line 37, in index
    return render_template('index.html', title='Home', form=form,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2023-11-27 10:35:58,509 ERROR: Exception on /index [GET] [in C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\routes.py", line 37, in index
    return render_template('index.html', title='Home', form=form,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2023-11-27 10:37:08,320 INFO: Microblog startup [in C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\__init__.py:47]
2023-11-27 11:11:54,059 INFO: Microblog startup [in C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\__init__.py:47]
