2023-11-27 11:11:55,841 ERROR: Exception on /login [GET] [in C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\routes.py", line 71, in login
    return render_template('login.html', title='Sign In', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block scripts %}
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\templates\base.html", line 54, in block 'scripts'
    {{ moment.include_moment() }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'moment' is undefined
2023-11-27 11:11:56,017 ERROR: Exception on /login [GET] [in C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\routes.py", line 71, in login
    return render_template('login.html', title='Sign In', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block scripts %}
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\templates\base.html", line 54, in block 'scripts'
    {{ moment.include_moment() }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'moment' is undefined
2023-11-27 11:12:10,454 INFO: Microblog startup [in C:\Users\STUDENT.LAPTOP-67\Desktop\globodain\microblog\app\__init__.py:47]
